name: pizz_lecious
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  bloc: ^8.1.4

  user_repository:
    path: backendservices/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
