// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1QRIHby0lF01C1nxFqMUZFhltL2fb5k',
    appId: '1:406416057443:web:655ddf4dc1d33957e40456',
    messagingSenderId: '406416057443',
    projectId: 'pizz-lecious',
    authDomain: 'pizz-lecious.firebaseapp.com',
    storageBucket: 'pizz-lecious.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANGgg9tP_dIvuko8ZzrebM4961NpmF3fc',
    appId: '1:406416057443:android:ae35b044bf71a1b6e40456',
    messagingSenderId: '406416057443',
    projectId: 'pizz-lecious',
    storageBucket: 'pizz-lecious.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGNbN8sdIEmu8Ui2pNrWVkbUz8ymZ2iw',
    appId: '1:406416057443:ios:6425360e4c75f360e40456',
    messagingSenderId: '406416057443',
    projectId: 'pizz-lecious',
    storageBucket: 'pizz-lecious.firebasestorage.app',
    iosBundleId: 'com.example.pizzLecious',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGNbN8sdIEmu8Ui2pNrWVkbUz8ymZ2iw',
    appId: '1:406416057443:ios:6425360e4c75f360e40456',
    messagingSenderId: '406416057443',
    projectId: 'pizz-lecious',
    storageBucket: 'pizz-lecious.firebasestorage.app',
    iosBundleId: 'com.example.pizzLecious',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG1QRIHby0lF01C1nxFqMUZFhltL2fb5k',
    appId: '1:406416057443:web:535eedb67901f60fe40456',
    messagingSenderId: '406416057443',
    projectId: 'pizz-lecious',
    authDomain: 'pizz-lecious.firebaseapp.com',
    storageBucket: 'pizz-lecious.firebasestorage.app',
  );
}
